#!/usr/bin/env python3
"""Guard against GitHub Actions expression injection into executable bodies.

Motivating defect (#3820): the developer agent's fatal-error escalation step
built its JavaScript by interpolating ``${{ ... }}`` workflow expressions
*inside single-quoted JS string literals*::

    const phase3Diagnosis = '${{ steps.claude_result.outputs.diagnosis }}';

``${{ }}`` substitution happens before the script is parsed, so the substituted
text becomes JavaScript *source*. A diagnosis containing an apostrophe (the
norm in free-form prose) terminates the literal early and leaves bare
identifiers behind -- the observed ``SyntaxError: Unexpected identifier
'issues'``. The step that exists to report fatal errors crashed before
reporting anything, so the run's real failure was never surfaced.

It is not merely a quoting bug: these steps hold ``github-token``, so whatever
the substituted text parses as executes with that token.

**The class is one construct wider than #3820 swept (#3837, ledger V-044).**
The fault was named as "an expression interpolated into a ``script:`` body is
JavaScript, not data", so the sweep and this guard both stopped at ``script:``.
The true class is *any executable body*: a ``run:`` block is **shell** source,
substituted by the same pre-parse pass. CodeQL alert #124 found the identical
injection in ``huddle_decision_dispatch.yml``, where a step output was
substituted into a ``run:`` block and then flowed into a nested ``bash -lc``
-- a quote in the value escapes two shells, in a job carrying an agent token.

The supported shape is GitHub's documented one -- pass the value through
``env:`` and read it as data, never as source::

    env:
      PHASE3_DIAGNOSIS: ${{ steps.claude_result.outputs.diagnosis }}
    with:
      script: |
        const phase3Diagnosis = process.env.PHASE3_DIAGNOSIS;

    env:
      DECISION: ${{ steps.decide.outputs.decision }}
    run: |
        echo "$DECISION"

The two body kinds are held to deliberately different rules:

``script:``
    **No ``${{`` at all.** A github-script body never needs one -- every value
    it can want is reachable through ``env:`` or the ``context`` object -- so
    an absolute rule costs nothing and cannot rot.

``run:``
    **Only shape-constrained, repo-controlled expressions** (`SAFE_IN_RUN`).
    An absolute rule here would be 593 rewrites of ``${{ vars.REPO_OWNER }}``
    and friends, whose values are repo configuration written by admins -- the
    same trust level as the workflow file itself. What must go through
    ``env:`` is everything whose value is *not* visible at the interpolation
    site: step and job outputs (this is exactly the #3820 lesson -- the
    ``diagnosis`` output looked fine at its use site), ``inputs`` and
    ``github.event.inputs`` (typed by whoever dispatched the run), matrix
    values built from generated JSON, ``github.ref``/``head_ref`` (a git
    branch name may legally contain a quote), and any free-text event field.

This module finds any remaining violation. It is used by
``tests/unit/test_workflow_script_injection.py`` and runnable as a CLI.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path

import yaml

#: Directory scanned when no explicit paths are given.
DEFAULT_WORKFLOW_DIR = Path(".github/workflows")

#: The construct that must never appear in a ``script:`` body.
EXPRESSION_OPEN = "${{"

#: One ``${{ ... }}`` expression, non-greedy so several on a line are separate.
EXPRESSION = re.compile(r"\$\{\{(.*?)\}\}", re.DOTALL)

#: Expressions a ``run:`` body may interpolate directly.
#:
#: Every entry is here because its value is either written by a repository
#: admin (the same trust level as the workflow file) or structurally
#: constrained by GitHub to a character set that cannot terminate a shell
#: word. Anything not matched here must be passed through ``env:``.
#:
#: Deliberately absent, and worth naming because they look safe:
#:   ``github.ref`` / ``github.ref_name`` / ``github.head_ref`` -- a git
#:   branch name may contain a single quote, which is GitHub's own canonical
#:   ``run:``-injection example.
#:   ``secrets.*`` -- masked in logs, but still substituted as shell source,
#:   and a secret is exactly the value that must not end up in an ``xtrace``
#:   line or an argv another process can read.
SAFE_IN_RUN: tuple[str, ...] = (
    # Repository/organization configuration variables: written only by repo
    # admins, i.e. by whoever could edit the workflow anyway.
    r"vars\.[A-Za-z_][A-Za-z0-9_]*",
    # Run and repository identity generated by GitHub, not by any user.
    r"github\.(?:repository|repository_owner|repository_id|repositoryUrl"
    r"|workflow|run_id|run_number|run_attempt|job|action|event_name|sha"
    r"|api_url|server_url|graphql_url|workspace)",
    # Login handles: GitHub constrains these to [A-Za-z0-9-] plus [bot].
    r"github\.(?:actor|actor_id|triggering_actor)",
    # Runner-provided paths and platform facts.
    r"runner\.(?:os|arch|name|temp|tool_cache|workspace|debug)",
    # Numeric identifiers anywhere in the event payload (issue/PR/comment
    # numbers and ids are integers serialized by GitHub).
    r"github\.event(?:\.[A-Za-z_][A-Za-z0-9_]*)*\.(?:number|id)",
)

_SAFE_IN_RUN_RE = re.compile("|".join(f"(?:{p})" for p in SAFE_IN_RUN))


@dataclass(frozen=True)
class Violation:
    """One ``${{ ... }}`` expression interpolated into an executable body."""

    path: Path
    job: str
    step: str
    line: int
    text: str
    kind: str = "script"

    def format(self) -> str:
        return f"{self.path}:{self.line}: [{self.job} / {self.step}] ({self.kind}:) {self.text}"


@dataclass(frozen=True)
class ScriptStep:
    """A workflow step carrying an inline executable body.

    ``kind`` is ``"script"`` for an ``actions/github-script`` ``with.script``
    body (JavaScript) and ``"run"`` for a ``run:`` block (shell).
    """

    path: Path
    job: str
    step: str
    line: int
    script: str
    kind: str = "script"


def _step_name(step: dict, index: int) -> str:
    for key in ("name", "id"):
        value = step.get(key)
        if isinstance(value, str) and value:
            return value
    return f"step[{index}]"


def _script_start_line(path: Path, script: str) -> int:
    """Best-effort 1-based line of a script body's first line.

    ``yaml.safe_load`` discards positions, and re-parsing with a node-tracking
    loader would still not survive the block-scalar folding, so anchor on the
    first non-empty line of the body instead. Line numbers here are a
    navigation aid for the report; correctness of the scan does not rest on
    them.
    """
    first = next((ln for ln in script.splitlines() if ln.strip()), "")
    if not first:
        return 1
    needle = first.strip()
    for number, line in enumerate(path.read_text().splitlines(), start=1):
        if line.strip() == needle:
            return number
    return 1


def is_safe_in_run(expression: str) -> bool:
    """True when ``expression`` may be interpolated into a ``run:`` body.

    ``expression`` is the text between the ``${{`` and ``}}`` delimiters. An
    expression that is not a bare context read -- a function call, a ``||``
    default, a comparison -- is never safe: its result shape is not visible
    here, so it goes through ``env:`` like everything else.
    """
    return bool(_SAFE_IN_RUN_RE.fullmatch(expression.strip()))


def iter_script_steps(path: Path) -> Iterator[ScriptStep]:
    """Yield every step in ``path`` with an inline ``with.script`` or ``run:``."""
    try:
        document = yaml.safe_load(path.read_text())
    except yaml.YAMLError as exc:  # pragma: no cover - malformed workflow
        raise ValueError(f"{path}: not parseable as YAML: {exc}") from exc
    if not isinstance(document, dict):
        return
    jobs = document.get("jobs")
    if not isinstance(jobs, dict):
        return
    for job_name, job in jobs.items():
        if not isinstance(job, dict):
            continue
        steps = job.get("steps")
        if not isinstance(steps, list):
            continue
        for index, step in enumerate(steps):
            if not isinstance(step, dict):
                continue
            bodies: list[tuple[str, str]] = []
            with_block = step.get("with")
            if isinstance(with_block, dict) and isinstance(with_block.get("script"), str):
                bodies.append(("script", with_block["script"]))
            if isinstance(step.get("run"), str):
                bodies.append(("run", step["run"]))
            for kind, body in bodies:
                yield ScriptStep(
                    path=path,
                    job=str(job_name),
                    step=_step_name(step, index),
                    line=_script_start_line(path, body),
                    script=body,
                    kind=kind,
                )


def _line_violations(step: ScriptStep, offset: int, line: str) -> list[Violation]:
    """Classify the expressions on one line of ``step``'s body."""
    if EXPRESSION_OPEN not in line:
        return []
    if step.kind == "run":
        # Only the expressions outside SAFE_IN_RUN are reported. An unbalanced
        # `${{` (a multi-line expression, or a typo) matches nothing and is
        # reported too -- unclassifiable is not the same as safe.
        found = EXPRESSION.findall(line)
        unsafe = [e.strip() for e in found if not is_safe_in_run(e)]
        if found and not unsafe:
            return []
    return [
        Violation(
            path=step.path,
            job=step.job,
            step=step.step,
            line=step.line + offset,
            text=line.strip(),
            kind=step.kind,
        )
    ]


def find_violations(paths: Sequence[Path]) -> list[Violation]:
    """Return every disallowed ``${{`` interpolation in an executable body."""
    violations: list[Violation] = []
    for path in paths:
        for step in iter_script_steps(path):
            for offset, line in enumerate(step.script.splitlines()):
                violations.extend(_line_violations(step, offset, line))
    return violations


def workflow_files(directory: Path = DEFAULT_WORKFLOW_DIR) -> list[Path]:
    """Return every workflow file under ``directory``, sorted by name."""
    return sorted([p for p in directory.iterdir() if p.suffix in (".yml", ".yaml") and p.is_file()])


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="workflow files to scan (default: every file in .github/workflows)",
    )
    args = parser.parse_args(argv)

    paths = args.paths or workflow_files()
    if not paths:
        print("No workflow files to scan.", file=sys.stderr)
        return 1

    violations = find_violations(paths)
    if not violations:
        print(
            f"OK: no ${{{{ }}}} interpolation in {len(paths)} workflow "
            "script: or run: bodies (beyond the repo-controlled allowlist)."
        )
        return 0

    print(
        f"{len(violations)} GitHub Actions expression(s) interpolated into an "
        "executable body (github-script `script:` or shell `run:`):",
        file=sys.stderr,
    )
    for violation in violations:
        print(f"  {violation.format()}", file=sys.stderr)
    print(
        "\nPass these values through `env:` and read them as data -- "
        '`process.env.NAME` in a script: body, "$NAME" in a run: body '
        "(#3820, #3837).",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
