apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyxgpt
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - hpa-blue.yaml
  - hpa-green.yaml
  - deployment-stable.yaml
  - deployment-canary.yaml
  - service-canary.yaml
