apiVersion: v1
kind: Service
metadata:
  name: nyxgpt-api
  namespace: nyxgpt
spec:
  selector:
    app: nyxgpt-api
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
