#!/usr/bin/env python3
"""Generate agents/CONTEXT_INDEX.md -- the map agents read instead of the territory.

The bootstrap used to tell every agent to read `.github/workflows/*` and
`scripts/agents/*` in full: ~97k words, ~70% of the whole bootstrap corpus,
almost none of it relevant to any one run. This index states what each file
is in one line, so an agent knows what exists and opens only what it needs.

Regenerate with `python3 scripts/build_context_index.py`; the paired test
fails if the committed copy has drifted.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
INDEX_PATH = REPO_ROOT / "agents" / "CONTEXT_INDEX.md"

HEADER = """# Agent context index

**Read this instead of reading every workflow and script.** One line per file:
what it is, and (for workflows) what starts it. Open a file only when the task
in hand needs its detail -- see `CLAUDE.md` section Bootstrap.

Generated by `scripts/build_context_index.py`; `tests/unit/test_context_index.py`
fails if it drifts. Do not hand-edit.
"""

SKIP_PREFIXES = ("#!", "set -", "IFS=", "export ", "shopt ")
COMMENT_NOISE = ("shellcheck", "vim:", "set -")
DOCSTRING_MARKS = ('"""', "'''")


def _workflow_triggers(text: str) -> str:
    """Summarize a workflow's `on:` block without a YAML parse.

    Deliberately textual: these files carry multi-line `if:` expressions that a
    strict parse would choke on, and all we need here is the trigger names.
    """
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if re.match(r"^on:\s*$", line))
    except StopIteration:
        match = re.search(r"^on:\s*(.+)$", text, re.MULTILINE)
        return match.group(1).strip() if match else "?"

    triggers = []
    for line in lines[start + 1 :]:
        if line and not line.startswith((" ", "\t")):
            break
        found = re.match(r"^  ([a-z_]+):", line)
        if found:
            triggers.append(found.group(1))
    return ", ".join(triggers) or "?"


def _workflow_name(text: str, path: Path) -> str:
    match = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip().strip("\"'") if match else path.stem


def _strip_self_reference(body: str) -> str:
    """Drop a leading `path/name.sh --` prefix; the table already names the file."""
    stripped = re.sub(r"^(?:[\w./-]*/)?[\w.-]+\.(?:sh|py)\s*(?:[-—:]+\s*)?", "", body)
    return stripped.strip()


def _is_prose(line: str) -> bool:
    """Reject argument synopses; a purpose line has to read like a sentence."""
    if line.startswith(("[", "<", "-", "|")):
        return False
    return len(line.split()) >= 4


def _first_sentence(lines: list[str], index: int) -> str:
    """Join a wrapped comment block into one sentence, so it does not truncate."""
    parts = []
    for line in lines[index:]:
        stripped = line.strip()
        if not stripped.startswith("#"):
            break
        body = stripped.lstrip("#").strip()
        if not body:
            break
        parts.append(body)
        if body.endswith((".", ":")):
            break
    sentence = " ".join(parts)
    sentence = sentence.split(". ")[0].rstrip(".:")
    return sentence[:130].strip()


def _script_purpose(text: str) -> str:
    """One-line description of a script.

    Header comments in this tree sit in three places: above the shebang body,
    below `set -euo pipefail`, or -- for scripts that document themselves to
    the operator instead -- only inside a `usage()` heredoc. All three are
    read, because a script with no line here is a script an agent has to open.
    """
    lines = text.splitlines()
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith(SKIP_PREFIXES):
            continue
        if stripped.startswith("#"):
            body = stripped.lstrip("#").strip()
            if not body or set(body) <= {"-", "=", "#"}:
                continue
            if body.startswith(COMMENT_NOISE):
                continue
            cleaned = _strip_self_reference(_first_sentence(lines, index))
            if cleaned:
                return cleaned
            continue
        if stripped.startswith(DOCSTRING_MARKS):
            body = _strip_self_reference(stripped.strip("\"'").strip()).rstrip(".")
            if body:
                return body
            continue
        break

    usage = re.search(r"usage\(\)\s*\{\s*\n\s*cat <<-?'?\w+'?\s*\n(.*?)\nEOF", text, re.S)
    if usage:
        for candidate in usage.group(1).splitlines():
            candidate = _strip_self_reference(candidate.strip()).rstrip(".")
            if candidate and not candidate.lower().startswith("usage:") and _is_prose(candidate):
                return candidate
    return "(no header comment)"


def build() -> str:
    out = [HEADER, "\n## Workflows (`.github/workflows/`)\n"]
    out.append("| Workflow | Triggered by | Name |")
    out.append("|---|---|---|")
    for path in sorted((REPO_ROOT / ".github" / "workflows").glob("*.yml")):
        text = path.read_text(encoding="utf-8")
        out.append(f"| `{path.name}` | {_workflow_triggers(text)} | {_workflow_name(text, path)} |")

    out.append("\n## Agent scripts (`scripts/agents/`)\n")
    out.append("| Script | Purpose |")
    out.append("|---|---|")
    for path in sorted((REPO_ROOT / "scripts" / "agents").glob("*.sh")):
        purpose = _script_purpose(path.read_text(encoding="utf-8"))
        out.append(f"| `{path.name}` | {purpose} |")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    INDEX_PATH.write_text(build(), encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
