#!/usr/bin/env bash
set -euo pipefail

# QA Agent: Generate QA Report
# Usage: qa_report.sh <PR_NUMBER> <TEST_RESULTS_FILE>

PR_NUMBER="$1"
TEST_RESULTS_FILE="${2:-qa_results.txt}"
REPORT_FILE="qa_report_${PR_NUMBER}.md"

echo "[INFO] Generating QA report for PR #${PR_NUMBER}..."

# Get PR details
PR_TITLE=$(gh pr view "$PR_NUMBER" --json title -q '.title')
PR_AUTHOR=$(gh pr view "$PR_NUMBER" --json author -q '.author.login')

# Parse test results
UNIT_PASS=false
INTEGRATION_PASS=false
E2E_PASS=false

if grep -q "Unit Tests:.*PASS" "$TEST_RESULTS_FILE" 2>/dev/null; then
    UNIT_PASS=true
fi

if grep -q "Integration Tests:.*PASS" "$TEST_RESULTS_FILE" 2>/dev/null; then
    INTEGRATION_PASS=true
fi

if grep -q "E2E Tests:.*PASS" "$TEST_RESULTS_FILE" 2>/dev/null; then
    E2E_PASS=true
fi

# Determine overall status
if [ "$UNIT_PASS" = true ] && [ "$INTEGRATION_PASS" = true ] && [ "$E2E_PASS" = true ]; then
    OVERALL_STATUS="PASS ✓"
    RECOMMENDATION="APPROVE - All automated tests pass. This PR is ready for merge after manual verification."
else
    OVERALL_STATUS="FAIL ✗"
    RECOMMENDATION="BLOCK - Test failures detected. See details below. Manual intervention required for blocking failures."
fi

# Extract test counts
UNIT_COUNT=$(grep -o "[0-9]* passed" "$TEST_RESULTS_FILE" | head -1 || echo "0 passed")
INTEGRATION_COUNT=$(grep -o "[0-9]* passed" "$TEST_RESULTS_FILE" | tail -1 || echo "0 passed")

# Extract failures
FAILURES=$(grep -A 5 "FAILED\|ERROR\|FAIL ✗" "$TEST_RESULTS_FILE" | head -50 || echo "None")

# Load manual test results if available
MANUAL_RESULTS_FILE="qa_manual_results_${PR_NUMBER}.txt"
MANUAL_RESULTS="Not executed"
if [ -f "$MANUAL_RESULTS_FILE" ]; then
    MANUAL_RESULTS=$(cat "$MANUAL_RESULTS_FILE")
fi

# Generate report
cat > "$REPORT_FILE" <<EOF
## QA Report: PR #${PR_NUMBER}

**PR Title:** ${PR_TITLE}
**Author:** @${PR_AUTHOR}
**QA Agent:** @myGPT-qa-agent
**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

---

### Overall Status: ${OVERALL_STATUS}

---

### Automated Test Results

| Test Suite | Status | Details |
|------------|--------|---------|
| Unit Tests | $([ "$UNIT_PASS" = true ] && echo '✓ PASS' || echo '✗ FAIL') | $UNIT_COUNT |
| Integration Tests | $([ "$INTEGRATION_PASS" = true ] && echo '✓ PASS' || echo '✗ FAIL') | $INTEGRATION_COUNT |
| E2E Tests (WebUI) | $([ "$E2E_PASS" = true ] && echo '✓ PASS' || echo '✗ SKIP') | Playwright |

---

### Manual Smoke Test Results

\`\`\`
${MANUAL_RESULTS}
\`\`\`

---

### Test Failures

$(if [ "$OVERALL_STATUS" = "PASS ✓" ]; then
    echo "No failures detected. All tests passed."
else
    echo "\`\`\`"
    echo "$FAILURES"
    echo "\`\`\`"
fi)

---

### Recommendation

**${RECOMMENDATION}**

---

### Next Steps

$(if [ "$OVERALL_STATUS" = "PASS ✓" ]; then
    echo "- ✓ All automated tests pass"
    echo "- ✓ Ready for final review and merge"
    echo "- Label: \`qa-pass\`"
else
    echo "- ✗ Test failures must be fixed before merge"
    echo "- ✗ Manual intervention required for blocking failures"
    echo "- ✗ Assign back to developer-agent for fixes"
    echo "- Label: \`qa-fail\`"
fi)

---

<details>
<summary>Full Test Output</summary>

\`\`\`
$(cat "$TEST_RESULTS_FILE")
\`\`\`

</details>

---

**Generated by qa-agent** | [QA Runbook](../RUNBOOKS/qa-runbook.md)
EOF

echo "[INFO] QA report generated: $REPORT_FILE"
cat "$REPORT_FILE"
echo ""
echo "[INFO] To post this report to PR #${PR_NUMBER}:"
echo "  gh pr comment $PR_NUMBER --body-file $REPORT_FILE"
