"""Unit tests for wrapped credential retrieval (`nyxgpt ops credentials`, #3718).

Covers every source a credential can really come from -- the config.ini
override, the ops-managed secret file, and the values `nyxgpt ops
glitchtip-init` provisions back into config.ini -- plus the two properties
the issue's security constraint rests on: nothing is generated by a read,
and no password reaches the logs.
"""

import json
import logging
from configparser import ConfigParser
from pathlib import Path
from types import SimpleNamespace

import pytest

from nyxgpt import config as config_mod
from nyxgpt import ops

BASE_CONFIG = """\
[nyxgpt]
default_model = llama3.1:8b

[ollama]
host = http://localhost:11434

[monitoring]
enabled = true
grafana_ui_url = http://localhost:3001

[error_tracking]
enabled = true
glitchtip_ui_url = http://localhost:8080
"""


@pytest.fixture
def cfg_path(tmp_path: Path) -> Path:
    """A config.ini with both observability sections but no credentials yet."""
    path = tmp_path / "config.ini"
    path.write_text(BASE_CONFIG, encoding="utf-8")
    # load_config caches on (path, mtime); a fresh tmp path per test is enough
    # to keep tests from reading each other's parser.
    return path


@pytest.fixture
def secret_path(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect the ops-managed Grafana secret file into the temp dir."""
    path = tmp_path / "secrets" / "grafana-admin-password"
    monkeypatch.setattr(config_mod, "grafana_admin_password_path", lambda: path)
    return path


def _by_service(creds: list[ops.ServiceCredential]) -> dict[str, ops.ServiceCredential]:
    return {c.service: c for c in creds}


# --- Grafana: the three ways its password can be resolved -----------------


@pytest.mark.unit
def test_grafana_credential_prefers_config_ini_override(cfg_path, secret_path):
    """An explicit `[monitoring] grafana_admin_password` wins over the secret file."""
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text("ops-managed-pw")
    cfg_path.write_text(
        BASE_CONFIG.replace(
            "[monitoring]\nenabled = true",
            "[monitoring]\nenabled = true\ngrafana_admin_password = override-pw",
        ),
        encoding="utf-8",
    )

    grafana = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["grafana"]

    assert grafana.password == "override-pw"  # pragma: allowlist secret
    assert grafana.username == "admin"
    assert grafana.url == "http://localhost:3001"
    assert "grafana_admin_password" in grafana.source
    assert grafana.available


@pytest.mark.unit
def test_grafana_credential_falls_back_to_ops_managed_secret_file(cfg_path, secret_path):
    """With no override, the generated-once secret `ops install` wrote is used,
    and the operator is told which file answered."""
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text("ops-managed-pw\n")

    grafana = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["grafana"]

    assert grafana.password == "ops-managed-pw"  # pragma: allowlist secret
    assert grafana.source == str(secret_path)


@pytest.mark.unit
def test_grafana_credential_reports_remediation_when_unprovisioned(cfg_path, secret_path):
    """Nothing provisioned yet is an answer, not a crash -- and it names the
    wrapped command that fixes it."""
    grafana = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["grafana"]

    assert not grafana.available
    assert grafana.password == ""
    assert "nyxgpt ops install" in grafana.remediation


@pytest.mark.unit
def test_reading_credentials_never_generates_a_grafana_password(cfg_path, secret_path):
    """Merely *asking* must not mint a secret: a password no running Grafana
    was ever reconciled to would be a confidently wrong login."""
    ops.resolve_service_credentials(cfg_path=cfg_path)

    assert not secret_path.exists()


# --- GlitchTip: the values `glitchtip-init` provisions --------------------


@pytest.mark.unit
def test_glitchtip_credential_reads_provisioned_values(cfg_path, secret_path):
    """`_persist_admin_credentials` (what `glitchtip-init` calls) writes the
    credentials this command then reports."""
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "provisioned-pw")

    glitchtip = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["glitchtip"]

    assert glitchtip.password == "provisioned-pw"  # pragma: allowlist secret
    assert glitchtip.username == "admin@nyxgpt.local"
    assert glitchtip.url == "http://localhost:8080"
    assert str(cfg_path) in glitchtip.source


@pytest.mark.unit
def test_glitchtip_credential_defaults_username_when_unprovisioned(cfg_path, secret_path):
    glitchtip = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["glitchtip"]

    assert not glitchtip.available
    assert glitchtip.username == ops.GLITCHTIP_DEFAULT_ADMIN_EMAIL
    assert "nyxgpt ops glitchtip-init" in glitchtip.remediation


@pytest.mark.unit
def test_glitchtip_credential_survives_a_config_written_after_load(cfg_path, secret_path):
    """Reading config.ini directly (not the cached parser) is what makes a
    `glitchtip-init` run in the same process visible."""
    ops.resolve_service_credentials(cfg_path=cfg_path)  # warms load_config's cache
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "written-later")

    glitchtip = _by_service(ops.resolve_service_credentials(cfg_path=cfg_path))["glitchtip"]

    assert glitchtip.password == "written-later"  # pragma: allowlist secret


# --- The command itself ---------------------------------------------------


@pytest.mark.unit
def test_credentials_command_prints_both_services_and_exits_zero(cfg_path, secret_path, capsys):
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text("ops-managed-pw")
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "provisioned-pw")

    rc = ops.credentials(SimpleNamespace(config=str(cfg_path), service="all", json=False))

    out = capsys.readouterr().out
    assert rc == 0
    assert "ops-managed-pw" in out
    assert "provisioned-pw" in out
    assert "grafana" in out and "glitchtip" in out


@pytest.mark.unit
def test_credentials_command_exits_two_when_a_password_is_missing(cfg_path, secret_path, capsys):
    """A missing credential is a scriptable failure, not a silently empty field."""
    rc = ops.credentials(SimpleNamespace(config=str(cfg_path), service="all", json=False))

    assert rc == 2
    assert "(not provisioned)" in capsys.readouterr().out


@pytest.mark.unit
def test_credentials_command_filters_to_one_service(cfg_path, secret_path, capsys):
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "provisioned-pw")

    rc = ops.credentials(SimpleNamespace(config=str(cfg_path), service="glitchtip", json=False))

    out = capsys.readouterr().out
    assert rc == 0
    assert "glitchtip" in out
    assert "grafana" not in out


@pytest.mark.unit
def test_credentials_command_json_is_machine_readable(cfg_path, secret_path, capsys):
    """The cloud path parses this stdout over SSH, so it has to be pure JSON."""
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text("ops-managed-pw")
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "provisioned-pw")

    ops.credentials(SimpleNamespace(config=str(cfg_path), service="all", json=True))

    payload = json.loads(capsys.readouterr().out)
    assert [c["service"] for c in payload] == ["grafana", "glitchtip"]
    assert payload[0]["password"] == "ops-managed-pw"  # pragma: allowlist secret
    assert payload[1]["password"] == "provisioned-pw"  # pragma: allowlist secret
    assert all(c["available"] for c in payload)


@pytest.mark.unit
def test_credentials_command_never_logs_a_password(cfg_path, secret_path, caplog, capsys):
    """The whole point is that these values live on stdout only -- a log line
    carrying one would leak it straight back into Loki (#3458/#3466)."""
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text("ops-managed-pw")
    ops._persist_admin_credentials(cfg_path, "admin@nyxgpt.local", "provisioned-pw")

    with caplog.at_level(logging.DEBUG):
        ops.credentials(SimpleNamespace(config=str(cfg_path), service="all", json=False))

    capsys.readouterr()
    logged = "\n".join(
        [r.getMessage() for r in caplog.records] + [str(r.__dict__) for r in caplog.records]
    )
    assert "ops-managed-pw" not in logged
    assert "provisioned-pw" not in logged


# --- The API boundary the issue requires us to preserve -------------------


@pytest.mark.unit
def test_monitoring_api_payload_still_omits_the_grafana_password(cfg_path):
    """`GET /api/v1/monitoring` returns `get_monitoring_config` verbatim; adding
    a CLI reader must not have widened that dict (#3458/#3466)."""
    cfg_path.write_text(
        BASE_CONFIG.replace(
            "[monitoring]\nenabled = true",
            "[monitoring]\nenabled = true\ngrafana_admin_password = override-pw",
        ),
        encoding="utf-8",
    )
    cfg = ConfigParser()
    cfg.read(cfg_path)

    payload = config_mod.get_monitoring_config(cfg)

    assert "grafana_admin_password" not in payload
    assert "override-pw" not in json.dumps(payload)


@pytest.mark.unit
def test_read_grafana_admin_password_is_the_read_only_half_of_resolve(tmp_path, monkeypatch):
    """`resolve_` keeps its generate-and-persist behaviour; `read_` does not,
    and once `resolve_` has written one, `read_` reports that same value."""
    path = tmp_path / "secrets" / "grafana-admin-password"
    monkeypatch.setattr(config_mod, "grafana_admin_password_path", lambda: path)
    cfg = ConfigParser()

    assert config_mod.read_grafana_admin_password(cfg) == ("", "")
    assert not path.exists()

    generated = config_mod.resolve_grafana_admin_password(cfg)

    assert path.exists()
    assert config_mod.read_grafana_admin_password(cfg) == (generated, str(path))
